server.port=8083
spring.application.name=weekly-backend-service

# OpenSearch Configuration
opensearch.url=${OPENSEARCH_URL:https://observability.utility.trestleiq.com}
opensearch.username=${OPENSEARCH_USERNAME:developer}
opensearch.password=y5wQBMOFSaE$n81OF$be

# Logging
logging.level.com.trestleiq=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n